In [1]:
import cv2
from matplotlib import image
import matplotlib.pyplot as plt
import numpy as np
from math import sqrt, floor, ceil
from PIL import Image
import math

In [6]:
img= cv2.imread("./pikachu.png")

cv2.imwrite("pipi.png", img)
print(img)

'''
img = Image.open("img.png")
img = np.array(img)
di = img.shape
'''

[[[255 255 255]
  [254 254 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[254 254 254]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [255 255 255]]

 [[254 254 254]
  [255 255 255]
  [254 254 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [254 254 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [254 254 254]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [254 254 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


'\nimg = Image.open("img.png")\nimg = np.array(img)\ndi = img.shape\n'

In [29]:
print(cv2.imread("./pil.png") - cv2.imread("./opencv.png"))

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
def read_image(path):

    img = cv2.imread(path)  # path , cv2.IMREAD_GRAYSCALE
    
    
    cv2.imwrite("./opencv.png", img)
    cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
    '''
    dimg = Image.fromarray(img)
    dimg.save("./asda.png")
    dimg.show()
    '''
    
    size = img.shape
    dimension = (size[0], size[1])

    return img, size, dimension

In [ ]:
img, size, dimension = read_image("./image.png")
print(f"Image size is: {size}")

In [ ]:
def image_change_scale(img, dimension, scale=100, interpolation=cv2.INTER_LINEAR):

    scale /= 100
    new_dimension = (int(dimension[1]*scale), int(dimension[0]*scale))
    resized_img = cv2.resize(img, new_dimension, interpolation=interpolation)
    return resized_img

In [ ]:
scale_percent = 25  # percent of original image size
resized_img = image_change_scale(img, dimension, scale_percent)
print(f"Smalled Image size is: {resized_img.shape}")

In [ ]:
nn_img = image_change_scale(
resized_img, dimension, interpolation=cv2.INTER_NEAREST)

In [ ]:
def testimage(img1, img2):
    print(img1.shape)
    print(img2.shape)
    print(img2.ndim)
    print(img1.ndim)
    if img1.shape == img2.shape:
        return img1.ndim
    

In [ ]:
testlist = []

testlist.append(testimage(nn_img, img))
print(testlist)